baseURL = "https://www.lejeudutitre.com/"
languageCode = "fr-FR"
title = "Le jeu du titre"
theme = "ljdt"
googleAnalytics = "UA-163514620-1"

[outputs]
    home = ["html"]

[params]
    author = "LeChaps"
    subtitle = "Le jeu des obsédés...de la conversation"
    mail ="proposition@lejeudutitre.com"
    facebook = "https://www.facebook.com/lejeudutitre"
    twitter = "https://www.twitter.com/lejeudutitre"
    github = "https://github.com/lechaps/lejeudutitre"
    leetchi = "http://www.leetchi.com/c/www-lejeudutitre-com"